
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 28 12:46:28 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_PAREN = 43;
  public static final int NOT_EQUAL_TO = 28;
  public static final int TRIPLE_DOT = 52;
  public static final int INCREMENT = 36;
  public static final int GREATER_OR_EQUAL = 30;
  public static final int CONST = 7;
  public static final int RIGHT_SQUARE_BRACKET = 45;
  public static final int BOOL_CONSTANT = 48;
  public static final int GREATER = 29;
  public static final int CONTINUE = 17;
  public static final int CHAR_CONSTANT = 51;
  public static final int DECREMENT = 37;
  public static final int LESS = 31;
  public static final int MINUS = 23;
  public static final int SEMICOLON = 38;
  public static final int AND = 33;
  public static final int RECORD = 21;
  public static final int LESS_OR_EQUAL = 32;
  public static final int OR = 34;
  public static final int LEFT_BRACE = 46;
  public static final int COMMA = 40;
  public static final int CLASS = 4;
  public static final int PLUS = 22;
  public static final int IF = 8;
  public static final int THIS = 18;
  public static final int DOT = 41;
  public static final int NUMBER_CONSTANT = 49;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 35;
  public static final int LEFT_SQUARE_BRACKET = 44;
  public static final int SUPER = 19;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 24;
  public static final int PERCENT = 26;
  public static final int RIGHT_BRACE = 47;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int EQUAL_TO = 27;
  public static final int COLON = 39;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int GOTO = 20;
  public static final int WHILE = 10;
  public static final int EXTENDS = 16;
  public static final int LEFT_PAREN = 42;
  public static final int FORWARD_SLASH = 25;
  public static final int PRINT = 12;
  public static final int DO = 9;
  public static final int IDENTIFIER = 50;
}

